<a href="https://colab.research.google.com/github/rohanw2004/E--Governance-Digital-Service/blob/main/week%202/e_goverence_research.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 2 — Data Collection and Cleaning

## Project Title
Analysis of Digital Governance Adoption using E-Panchayat Data

## Objective
To clean, preprocess, and prepare governance datasets for analytical evaluation of digital adoption across Indian states.

### 1.IMPORTING LIBRARIES

importing library to on our required dataset

In [1]:
import pandas as pd

### 2.LOAD DATASET
loading a dataset o work on the actual course of project.

In [2]:
df =pd.read_csv("/content/e_goverance-dataset.csv")

### 3.INITIAL DATA INSPECTION.
Inspecting with te data available in the csv file to reasssure which datas are need to be cleand and to be filled

Checking if the file is fit properly

In [3]:
df.head()

,Si. No.,Unnamed: 1,States,Total Number of Village Panchayats & Equivalent,Gram Panchayat Development Plans Uploaded,Gram Panchayats Ported,Total Number of Block Panchayats & Equivalent,Block Panchayats Plan uploaded,Total Number of ZillaPanchayats& Equivalent,ZillaPanchayats Plan uploaded,Gram Panchayat on onboard,Gram Panchayat With Online Payment,Plans Uploaded,Total number(sum),Adoption percentage = (plans uploaded/ Total Panchayats)*100
0,1,Andhra Pradesh,Y,13371,13351,13073,660,660,13,13,0,0,NaN,NaN,NaN
1,2,Arunachal Pradesh,Y,2108,1577,2034,0,0,25,0,3,0,NaN,NaN,NaN
2,3,Assam,Y,2666,2119,2201,192,32,26,7,2174,855,NaN,NaN,NaN
3,4,Bihar,Y,8135,8135,8135,534,533,38,37,8135,7863,NaN,NaN,NaN
4,5,Chhattisgarh,Y,11658,11658,11657,146,146,27,26,11613,10836,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Si. No.                                                       31 non-null     object
 1   Unnamed: 1                                                    31 non-null     object
 2   States                                                        29 non-null     object
 3   Total Number of Village Panchayats & Equivalent               31 non-null     int64
 4   Gram Panchayat Development Plans Uploaded                     31 non-null     int64
 5   Gram Panchayats Ported                                        31 non-null     int64
 6   Total Number of Block Panchayats & Equivalent                 31 non-null     int64
 7   Block Panchayats Plan uploaded                                31 non-null     int64
 8   Total Number of ZillaPanchayats& Equivalent                   31 non-null     int64
 9   ZillaPanchayats Plan uploaded                                 31 non-null     int64
 10  Gram Panchayat on onboard                                     31 non-null     int64
 11  Gram Panchayat With Online Payment                            31 non-null     int64
 12  Plans Uploaded                                                0 non-null      float64
 13  Total number(sum)                                             0 non-null      float64
 14  Adoption percentage = (plans uploaded/ Total Panchayats)*100  0 non-null      float64
dtypes: float64(3), int64(9), object(3)
memory usage: 3.8+ KB

In [5]:
print(df.columns.tolist())

['Si. No.', 'Unnamed: 1', 'States', 'Total Number of Village Panchayats & Equivalent', 'Gram Panchayat Development Plans Uploaded', 'Gram Panchayats Ported', 'Total Number of Block Panchayats & Equivalent', 'Block Panchayats Plan uploaded', 'Total Number of ZillaPanchayats& Equivalent', 'ZillaPanchayats Plan uploaded', 'Gram Panchayat on onboard', 'Gram Panchayat With Online Payment', 'Plans Uploaded', 'Total number(sum)', 'Adoption percentage = (plans uploaded/ Total Panchayats)*100']

### 4.DATA CLEANING
cleaning the column names and unnecessary insights/space from the chart

In [6]:
df.columns = df.columns.str.strip()

### 5.DATA STANDARDIZATION
Before Handling missing values we will approximately standardized our data.
making categorical data consistency

In [7]:
df["States"] = df["States"].str.strip()

In [8]:
df["States"] = df["States"].str.title()

### 6.MISSING VALUE HANDLING
Checking all the missing value in the chart

In [9]:
df.isnull().sum()

Si. No.                                                          0
Unnamed: 1                                                       0
States                                                           2
Total Number of Village Panchayats & Equivalent                  0
Gram Panchayat Development Plans Uploaded                        0
Gram Panchayats Ported                                           0
Total Number of Block Panchayats & Equivalent                    0
Block Panchayats Plan uploaded                                   0
Total Number of ZillaPanchayats& Equivalent                      0
ZillaPanchayats Plan uploaded                                    0
Gram Panchayat on onboard                                        0
Gram Panchayat With Online Payment                               0
Plans Uploaded                                                  31
Total number(sum)                                               31
Adoption percentage = (plans uploaded/ Total Panchayats)*100    31
dtype: int64

In [10]:
df['States'].fillna('Unknown', inplace=True)

/tmp/ipykernel_688/1183577084.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['States'].fillna('Unknown', inplace=True)

### 7.DATA TYPE CONVERSION
as I have heard that Government stores the data not just in numbers but alsp in alphabets, digits, symbols. To check we will perform:

In [11]:
numeric_columns = [
    "Gram Panchayat Development Plans Uploaded",
    "Block Panchayats Plan uploaded",
    "ZillaPanchayats Plan uploaded",
    "Total Number of Village Panchayats & Equivalent",
    "Total Number of Block Panchayats & Equivalent",
    "Total Number of ZillaPanchayats& Equivalent"
]

for col in numeric_columns:
   df[col] = pd.to_numeric(df[col], errors="coerce")

### 8.DUPLICATE VALIDATION
Checking if the duplicates exist in the file to remove them and make it clear sheet for analysis.(For duplicate Vldation)

In [12]:
df.duplicated().sum()

np.int64(0)

Cleaning all the duplicate data to make it a clear working and analysis based data file. (Performing for safety even i can see there is no duplicte existing)

In [13]:
df.drop_duplicates(inplace=True)

### 9. FEATURE ENGINEERING
Here, No we will sum all the required information from the data which is been used by government.

First, plans uploaded

In [14]:
df["Plans Uploaded"] = (
    df["Gram Panchayat Development Plans Uploaded"] +
    df["Block Panchayats Plan uploaded"] +
    df["ZillaPanchayats Plan uploaded"]
)

Then, Total number of blocks

In [15]:
df["Total number(sum)"] = (
    df["Total Number of Village Panchayats & Equivalent"] +
    df["Total Number of Block Panchayats & Equivalent"] +
    df["Total Number of ZillaPanchayats& Equivalent"]
)

Now, We are Going to rationalize the data divisional information based on project.

In [16]:
df["Adoption percentage = (plans uploaded/ Total Panchayats)*100"] = (
    df["Plans Uploaded"] /
    df["Total number(sum)"]
) * 100

### 10.DATA VALIDATION

Here, in this step, finding the unique data of appropriate data-column states.

In [17]:
df["States"].nunique()

3

checking for the impossible adoption

In [18]:
df[
      df["Adoption percentage = (plans uploaded/ Total Panchayats)*100"] > 100
    ]

Empty DataFrame
Columns: [Si. No., Unnamed: 1, States, Total Number of Village Panchayats & Equivalent, Gram Panchayat Development Plans Uploaded, Gram Panchayats Ported, Total Number of Block Panchayats & Equivalent, Block Panchayats Plan uploaded, Total Number of ZillaPanchayats& Equivalent, ZillaPanchayats Plan uploaded, Gram Panchayat on onboard, Gram Panchayat With Online Payment, Plans Uploaded, Total number(sum), Adoption percentage = (plans uploaded/ Total Panchayats)*100]
Index: []

checking the negative values in the dataset.

In [19]:
negative_values = df[
    (df.select_dtypes(include='number') < 0).any(axis=1)
]

negative_values

Empty DataFrame
Columns: [Si. No., Unnamed: 1, States, Total Number of Village Panchayats & Equivalent, Gram Panchayat Development Plans Uploaded, Gram Panchayats Ported, Total Number of Block Panchayats & Equivalent, Block Panchayats Plan uploaded, Total Number of ZillaPanchayats& Equivalent, ZillaPanchayats Plan uploaded, Gram Panchayat on onboard, Gram Panchayat With Online Payment, Plans Uploaded, Total number(sum), Adoption percentage = (plans uploaded/ Total Panchayats)*100]
Index: []

verifying the calculated columns

In [20]:
df[[
    "States",
    "Plans Uploaded",
    "Total number(sum)",
    "Adoption percentage = (plans uploaded/ Total Panchayats)*100"
]].head()

,States,Plans Uploaded,Total number(sum),Adoption percentage = (plans uploaded/ Total Panchayats)*100
0,Y,14024,14044,99.857590
1,Y,1577,2133,73.933427
2,Y,2158,2884,74.826630
3,Y,8705,8707,99.977030
4,Y,11830,11831,99.991548

Checking the data types.

In [21]:
df.dtypes

Si. No.                                                          object
Unnamed: 1                                                       object
States                                                           object
Total Number of Village Panchayats & Equivalent                   int64
Gram Panchayat Development Plans Uploaded                         int64
Gram Panchayats Ported                                            int64
Total Number of Block Panchayats & Equivalent                     int64
Block Panchayats Plan uploaded                                    int64
Total Number of ZillaPanchayats& Equivalent                       int64
ZillaPanchayats Plan uploaded                                     int64
Gram Panchayat on onboard                                         int64
Gram Panchayat With Online Payment                                int64
Plans Uploaded                                                    int64
Total number(sum)                                                 int64
Adoption percentage = (plans uploaded/ Total Panchayats)*100    float64
dtype: object

So, Describe call is used hee to check whether the data formatted is perfectly fit on its block. and to evaluate the data-source

In [22]:
df.describe()

,Total Number of Village Panchayats & Equivalent,Gram Panchayat Development Plans Uploaded,Gram Panchayats Ported,Total Number of Block Panchayats & Equivalent,Block Panchayats Plan uploaded,Total Number of ZillaPanchayats& Equivalent,ZillaPanchayats Plan uploaded,Gram Panchayat on onboard,Gram Panchayat With Online Payment,Plans Uploaded,Total number(sum),Adoption percentage = (plans uploaded/ Total Panchayats)*100
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,17480.387097,16452.967742,15403.612903,429.806452,345.161290,42.322581,31.032258,14152.322581,11721.096774,16829.161290,17952.516129,89.447133
std,48367.861181,45734.478490,43039.639747,1175.633798,952.566606,115.083560,85.212082,39815.039326,33356.978805,46751.235229,49641.883088,20.785954
min,185.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,189.000000,0.000000
25%,2387.000000,1386.000000,748.000000,33.000000,1.000000,10.000000,3.500000,166.500000,64.000000,1399.500000,2508.500000,87.973879
50%,6225.000000,4865.000000,4351.000000,192.000000,95.000000,22.000000,13.000000,3540.000000,3170.000000,5042.000000,6389.000000,98.826150
75%,12647.000000,12646.000000,12076.500000,347.500000,322.000000,32.500000,25.500000,10837.000000,7818.500000,13127.000000,13145.500000,99.867019
max,270946.000000,255021.000000,238756.000000,6662.000000,5350.000000,656.000000,481.000000,219361.000000,181677.000000,260852.000000,278264.000000,100.000000

Here, we will sort the values according to the given states

no divisional errors

In [23]:
df[df["Total number(sum)"] == 0]

Empty DataFrame
Columns: [Si. No., Unnamed: 1, States, Total Number of Village Panchayats & Equivalent, Gram Panchayat Development Plans Uploaded, Gram Panchayats Ported, Total Number of Block Panchayats & Equivalent, Block Panchayats Plan uploaded, Total Number of ZillaPanchayats& Equivalent, ZillaPanchayats Plan uploaded, Gram Panchayat on onboard, Gram Panchayat With Online Payment, Plans Uploaded, Total number(sum), Adoption percentage = (plans uploaded/ Total Panchayats)*100]
Index: []

### 11.EXPLORATORY DATA ANALYSIS(EDA)

Here, we will sort th values according to the states, to keep it in arranged ordered

In [24]:
df.sort_values(
    by="Adoption percentage = (plans uploaded/ Total Panchayats)*100",
    ascending=False
)[[
    "States",
    "Adoption percentage = (plans uploaded/ Total Panchayats)*100"
]].head(10)

   States  Adoption percentage = (plans uploaded/ Total Panchayats)*100
12      Y                                         100.000000
27      Y                                         100.000000
18      Y                                         100.000000
4       Y                                          99.991548
3       Y                                          99.977030
10      Y                                          99.935317
25      Y                                          99.932539
24      Y                                          99.876448
0       Y                                          99.857590
28      Y                                          99.854459

Here, we are filtering the data for analyzing

In [25]:
df[
    df["Adoption percentage = (plans uploaded/ Total Panchayats)*100"] > 80
]

,Si. No.,Unnamed: 1,States,Total Number of Village Panchayats & Equivalent,Gram Panchayat Development Plans Uploaded,Gram Panchayats Ported,Total Number of Block Panchayats & Equivalent,Block Panchayats Plan uploaded,Total Number of ZillaPanchayats& Equivalent,ZillaPanchayats Plan uploaded,Gram Panchayat on onboard,Gram Panchayat With Online Payment,Plans Uploaded,Total number(sum),Adoption percentage = (plans uploaded/ Total Panchayats)*100
0,1,Andhra Pradesh,Y,13371,13351,13073,660,660,13,13,0,0,14024,14044,99.857590
3,4,Bihar,Y,8135,8135,8135,534,533,38,37,8135,7863,8705,8707,99.977030
4,5,Chhattisgarh,Y,11658,11658,11657,146,146,27,26,11613,10836,11830,11831,99.991548
5,6,Goa,Y,191,191,191,0,0,2,1,177,26,192,193,99.481865
6,7,Gujarat,Y,14270,14042,14225,248,8,33,3,14210,11809,14053,14551,96.577555
7,8,Haryana,Y,6225,6154,6224,142,35,22,8,5861,3276,6197,6389,96.994835
8,9,Himachal Pradesh,Y,3615,3200,3611,81,76,12,11,3540,517,3287,3708,88.646170
10,11,Jharkhand,Y,4351,4348,4351,263,263,24,24,4349,4345,4635,4638,99.935317
11,12,Karnataka,Y,5965,4865,5965,229,159,31,18,5965,5899,5042,6225,80.995984
12,13,Kerala,Y,941,941,941,152,152,14,14,941,606,1107,1107,100.000000
13,14,Ladakh,Unknown,193,193,0,31,0,2,0,0,0,193,226,85.398230
14,15,Madhya Pradesh,Y,22741,22695,22741,313,309,51,51,22689,21775,23055,23105,99.783597
15,16,Maharashtra,Y,27898,27875,27403,351,72,34,4,26678,15381,27951,28283,98.826150
18,19,Mizoram,Y,834,834,834,0,0,0,0,834,828,834,834,100.000000
19,20,Nagaland,Y,1288,1195,662,0,0,0,0,5,0,1195,1288,92.779503
20,21,Odisha,Y,6798,6724,6798,314,313,30,30,6792,6635,7067,7142,98.949874
21,22,Punjab,Y,13248,13157,13248,151,143,22,20,12882,9879,13320,13421,99.247448
22,23,Rajasthan,Y,11307,11281,11234,352,331,33,25,10061,7774,11637,11692,99.529593
23,24,Sikkim,Y,185,161,185,0,0,4,4,172,102,165,189,87.301587
24,25,Tamil Nadu,Y,12525,12523,12496,388,381,37,30,11743,5874,12934,12950,99.876448
25,26,Telangana,Y,12769,12769,1,540,532,32,31,0,0,13332,13341,99.932539
26,27,Tripura,Y,1219,1178,1178,35,35,8,9,1178,1177,1222,1262,96.830428
27,28,Uttarakhand,Y,7791,7791,7789,95,95,13,13,7787,5846,7899,7899,100.000000
28,29,Uttar Pradesh,Y,58189,58189,58189,826,740,75,75,58189,57052,59004,59090,99.854459
29,30,West Bengal,Y,3341,3228,3229,344,333,22,21,3222,3170,3582,3707,96.628001
30,Total,Total,Total,270946,255021,238756,6662,5350,656,481,219361,181677,260852,278264,93.742633

correlating the analysis

In [26]:
df.corr(numeric_only=True)

,Total Number of Village Panchayats & Equivalent,Gram Panchayat Development Plans Uploaded,Gram Panchayats Ported,Total Number of Block Panchayats & Equivalent,Block Panchayats Plan uploaded,Total Number of ZillaPanchayats& Equivalent,ZillaPanchayats Plan uploaded,Gram Panchayat on onboard,Gram Panchayat With Online Payment,Plans Uploaded,Total number(sum),Adoption percentage = (plans uploaded/ Total Panchayats)*100
Total Number of Village Panchayats & Equivalent,1.000000,0.999226,0.997375,0.986495,0.979332,0.989205,0.986914,0.994908,0.990689,0.999247,0.999991,0.076776
Gram Panchayat Development Plans Uploaded,0.999226,1.000000,0.998408,0.985263,0.978679,0.987653,0.986276,0.996185,0.992375,0.999990,0.999204,0.112235
Gram Panchayats Ported,0.997375,0.998408,1.000000,0.979890,0.972827,0.984130,0.982593,0.998114,0.994834,0.998307,0.997266,0.116109
Total Number of Block Panchayats & Equivalent,0.986495,0.985263,0.979890,1.000000,0.996019,0.993494,0.990725,0.972176,0.965385,0.985935,0.987162,0.094120
Block Panchayats Plan uploaded,0.979332,0.978679,0.972827,0.996019,1.000000,0.986042,0.991581,0.963877,0.959656,0.979577,0.980072,0.121569
Total Number of ZillaPanchayats& Equivalent,0.989205,0.987653,0.984130,0.993494,0.986042,1.000000,0.993910,0.980787,0.973718,0.988075,0.989664,0.082305
ZillaPanchayats Plan uploaded,0.986914,0.986276,0.982593,0.990725,0.991581,0.993910,1.000000,0.979982,0.977437,0.986852,0.987353,0.113528
Gram Panchayat on onboard,0.994908,0.996185,0.998114,0.972176,0.963877,0.980787,0.979982,1.000000,0.997590,0.995945,0.994672,0.116497
Gram Panchayat With Online Payment,0.990689,0.992375,0.994834,0.965385,0.959656,0.973718,0.977437,0.997590,1.000000,0.992128,0.990384,0.117159
Plans Uploaded,0.999247,0.999990,0.998307,0.985935,0.979577,0.988075,0.986852,0.995945,0.992128,1.000000,0.999242,0.112478
Total number(sum),0.999991,0.999204,0.997266,0.987162,0.980072,0.989664,0.987353,0.994672,0.990384,0.999242,1.000000,0.077226
Adoption percentage = (plans uploaded/ Total Panchayats)*100,0.076776,0.112235,0.116109,0.094120,0.121569,0.082305,0.113528,0.116497,0.117159,0.112478,0.077226,1.000000

### 12.PRELIMINARY FINDINGS.

After cleaning and analyzing the E-Panchayat and e-Gram Swaraj dataset, several important observations were identified regarding digital governance adoption across Indian states.

1. The adoption percentage of digital governance services differs significantly from state to state. Some states show high participation in uploading Panchayat development plans, while others have lower adoption levels.

2. States with higher adoption percentages appear to have better implementation of digital governance systems and stronger usage of online Panchayat platforms.

3. The dataset indicates that digital governance in rural administration is growing, especially through online planning and Panchayat management systems.

4. Some states still show comparatively lower digital adoption, which may be due to differences in infrastructure, awareness, administrative efficiency, or technology accessibility.

5. During preprocessing and validation, no duplicate records, negative values, or logically incorrect adoption percentages were found. This suggests that the dataset is reliable for further analysis and visualization.

6. The calculated adoption percentage helped in comparing governance performance across states and identifying leading and lagging regions in digital governance implementation.

Overall, the dataset provides meaningful insights into the progress of Panchayat-level digital governance in India and forms a strong foundation for further visualization and policy analysis.

### 13.SAVE CLEAN DATA
Now, Finally saing the data chart which is cleaned to be used and clarified format

In [27]:
df.to_csv("e_panchayat_cleaned_v1.csv", index=False)